name: CI
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CD"]
    types:
       - completed
jobs:
  precheck:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install The Precheck
        run: bash .github/scripts/precheck/precheckBuild.sh
      - name: Sanitize The Precheck
        run: |
          sed -i 's/yaml manifest makefile consistency/makefile/g' .github/scripts/precheck/run-precheck.sh
          gzip -d -f gds/*
      - name: Run The Precheck
        run: bash .github/scripts/precheck/run-precheck.sh
  precheck-drc:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install The Precheck
        run: bash .github/scripts/precheck/precheckBuild.sh
      - name: Sanitize The Precheck
        run: |
          sed -i 's/yaml manifest makefile consistency/makefile/g' .github/scripts/precheck/run-precheck.sh
          gzip -d -f gds/*
      - name: Run The Precheck
        run: bash .github/scripts/precheck/run-precheck-drc.sh
  dv_rtl:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env: 
      OPENLANE_TAG: 2021.12.17_05.07.41
      CARAVEL_TAG: mpw-3a
      MAGIC_VERSION: 8.3.209
    steps:
       - uses: actions/checkout@v2
       - name: install deps
         run:  bash .github/scripts/build/run-install-magic.sh
       - name: Install Caravel
         run:  bash .github/scripts/build/run-pdk-build.sh
       - name: Run DV tests
         # Run test number 0,1,2,3,4 in one job       <test-ids>   <sim-mode>
         run: bash .github/scripts/dv/run-dv-tests.sh 4            RTL
  dv_gl:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env: 
      OPENLANE_TAG: 2021.12.17_05.07.41
      CARAVEL_TAG: mpw-3a
      MAGIC_VERSION: 8.3.209
    steps:
       - uses: actions/checkout@v2
       - name: install deps
         run:  bash .github/scripts/build/run-install-magic.sh
       - name: Install Caravel
         run:  bash .github/scripts/build/run-pdk-build.sh
       - name: Run DV tests
         # Run test number 0,1,2,3,4 in one job       <test-ids>   <sim-mode>
         run: bash .github/scripts/dv/run-dv-tests.sh 4            GL
